services:
  db:
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sentinel
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier

  api:
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sentinel
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_MAIL_SENDER_HOST:
      SPRING_MAIL_SENDER_PORT:
      SPRING_MAIL_SENDER_USERNAME:
      SPRING_MAIL_SENDER_PASSWORD:
      SMTP_MAIL:
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier:
